//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8825
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Petronode.Timepick.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Seismic_Raw_Folder {
            get {
                return ((string)(this["Seismic_Raw_Folder"]));
            }
            set {
                this["Seismic_Raw_Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Seismic_Selected_Shot_Folder {
            get {
                return ((string)(this["Seismic_Selected_Shot_Folder"]));
            }
            set {
                this["Seismic_Selected_Shot_Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*.s*")]
        public string Seismic_File_Mask {
            get {
                return ((string)(this["Seismic_File_Mask"]));
            }
            set {
                this["Seismic_File_Mask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Surface_Time_Min {
            get {
                return ((decimal)(this["Surface_Time_Min"]));
            }
            set {
                this["Surface_Time_Min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public decimal Surface_Time_Max {
            get {
                return ((decimal)(this["Surface_Time_Max"]));
            }
            set {
                this["Surface_Time_Max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal Surface_Vertical_Scale {
            get {
                return ((decimal)(this["Surface_Vertical_Scale"]));
            }
            set {
                this["Surface_Vertical_Scale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int Surface_Tuning {
            get {
                return ((int)(this["Surface_Tuning"]));
            }
            set {
                this["Surface_Tuning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public decimal Surface_Window {
            get {
                return ((decimal)(this["Surface_Window"]));
            }
            set {
                this["Surface_Window"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public decimal Surface_SNR {
            get {
                return ((decimal)(this["Surface_SNR"]));
            }
            set {
                this["Surface_SNR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Downhole_Time_Min {
            get {
                return ((decimal)(this["Downhole_Time_Min"]));
            }
            set {
                this["Downhole_Time_Min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public decimal Downhole_Time_Max {
            get {
                return ((decimal)(this["Downhole_Time_Max"]));
            }
            set {
                this["Downhole_Time_Max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal Downhole_Vertical_Scale {
            get {
                return ((decimal)(this["Downhole_Vertical_Scale"]));
            }
            set {
                this["Downhole_Vertical_Scale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int Downhole_Tuning {
            get {
                return ((int)(this["Downhole_Tuning"]));
            }
            set {
                this["Downhole_Tuning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Downhole_Window_Start {
            get {
                return ((decimal)(this["Downhole_Window_Start"]));
            }
            set {
                this["Downhole_Window_Start"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public decimal Downhole_Window {
            get {
                return ((decimal)(this["Downhole_Window"]));
            }
            set {
                this["Downhole_Window"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public decimal Downhole_SNR {
            get {
                return ((decimal)(this["Downhole_SNR"]));
            }
            set {
                this["Downhole_SNR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Display_Component {
            get {
                return ((int)(this["Display_Component"]));
            }
            set {
                this["Display_Component"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Timepick_Component {
            get {
                return ((int)(this["Timepick_Component"]));
            }
            set {
                this["Timepick_Component"] = value;
            }
        }
    }
}
